# 基底映像檔來自 Nvidia Pytorch Container 在 24 年 6 月釋出的版本
# 包含：Pytorch 2, OpenCV 4.7, Python 3.10
FROM nvcr.io/nvidia/pytorch:24.04-py3

# 這邊建議直接改成目前的資料夾位置
# 由於在建置 container 時，已經指定了內外的映射位置，這裡建議直接設置為共享的映射資料夾，傳輸檔案比較方便
WORKDIR /workspace/DiffuCE

# 安裝 git
# RUN apt-get update && apt-get install -y git

# 安裝 diffusers v0.29.2
RUN git clone --branch v0.29.2 --depth 1 https://github.com/huggingface/diffusers.git
# 切換到 diffusers 內安裝相依的函數庫
WORKDIR /workspace/DiffuCE/diffusers
RUN pip install .
# 切換到 text_to_image 中安裝相依的函數庫
WORKDIR /workspace/DiffuCE/diffusers/examples/text_to_image
RUN pip install -r requirements.txt

# 返回到 /workspace/DiffuCE
WORKDIR /workspace/DiffuCE

COPY requirements.txt .

# 安裝其餘相依函數庫
RUN pip install --no-cache-dir -r requirements.txt

# 特別處理 cv2
# 由於 albumentations 會固定下載 opencv-python-headless ，破壞 opencv 的完整功能
# 這裡要重新下載回 opencv-python
# 注意：Opencv 版本似乎會不定期變動，若 4.7.0 版本有新的變化，請在此更改
RUN pip uninstall -y opencv-python-headless
RUN pip install opencv-python==4.7.0.72

# 默認啟動命令
CMD ["bash"]
